### ISSUE TITLE
[Questions] BSLamp2 Bluetooth

### ISSUE THREAD

**Issue by hellcry37** [mmakaay/esphome-yeelight_bs2#111]
**Is your feature request related to a problem? Please describe.**
I noticed that my coordinator (Zigbee2MQTT) fails badly with interference errors if around one of my BSLamp 2.

**Describe the solution you'd like**
- Does bslamp2 have Bluetooth?
- If yes is it used for anything?
- If it has Bluetooth and is not used, can it be turned off (made not to tx at all)

**Describe alternatives you've considered**
Moving the lamp :)

**Comment by randybb** [comment]
Yes, that single core esp32 has BLE and it is not enabled.

If not the lamp, move the coordinator then :D

**Comment by hellcry37** [comment]
excelent :) Thanks
