### ISSUE TITLE
MCU temperature reading support?

### ISSUE THREAD

**Issue by szymucha94** [mmakaay/esphome-yeelight_bs2#112]
Is it safe to use this configuration: https://github.com/esphome/esphome/pull/4330
to send MCU temp to HA from these lamps?

**Comment by mmakaay** [comment]
I gave it a go for you, and it seems to work:
![image](https://user-images.githubusercontent.com/470371/226931486-d12fb1b7-3e32-4c78-b157-aa681acf7d33.png)

After flashing, my dev lamp did not correctly reboot and I had to disconnect and reconnect the power. I've never seen that happen and likely it has nothing to do with this new module. But in case the same thing happens with you: the power cycle does help ander after restarting, the temperature was reported. Subsequent flashes didn't show this behaviour, so might have been anything really 😄

**Comment by szymucha94** [comment]
Both of my lamps had the same issue with failed reboot. But it happened after keeping original, default configuration and just upgrading to 2023.3.0
Thank you, I will update my configuration then :)

**Comment by szymucha94** [comment]
I had troubles building this, but seems like cleaning build files fixed the issue. I get the readings now :) Thanks!

**Comment by mmakaay** [comment]
Great! And interesting you had the same failed reboot. Maybe something that got introduced with 2023.3.0.
I'll experiment a bit with that by doing some downgrade / upgrade cycles. Not important for this issue though.
Enjoy the temperature readings!
