### ISSUE TITLE
Question: Will the (yeelight) App still work? 

### ISSUE THREAD

**Issue by Madaraxa** [mmakaay/esphome-yeelight_bs2#113]
Hi.
I found your project because yeelight did cancel the LAN-Control through a Firmware Update.
As I still want to use the yeelight App (mainly to set a Color by clicking on it): is this still possible with your Firmware? Or Do i have to choose between 'Smarthome' and App :)?
I read that the cloud is disabled, but maybe the App still works in local Network?

**Comment by randybb** [comment]
I still can control all my Yeelight lamps via LAN, so not sure for which regions they disabled it.

And no, with this integration the lamp will work only with HomeAssistant or with anything that can control devices via MQTT (is not there by default, you can add it).

**Comment by martinrevert** [comment]
No, the Yeelight App only works on cloud mode and offer LAN control only for products branded as Yeelight. Maurice's project changes the firmware of bslamps to work on local LAN, so it will not work anymore with Yeelight cloud also. But if you're handy enough, you can add Home Assistant and that will give you more power and control, using de Home Assistant Mobile App companion. I strongly suggest that you explore that scenario if you want keep local control and mobile control of your bslamps.

**Comment by Madaraxa** [comment]
I got iobroker, which can handle esphome as well.
I have to use a vis then. Thanks for the answers
