### ISSUE TITLE
[QUESTION] Soldering RX/TX to ESP directly

### ISSUE THREAD

**Issue by rufik** [mmakaay/esphome-yeelight_bs2#77]
I've put too much force to pin soldered to TX pad and it came off :(
The only possibility is to solder into RX/TX directly on ESP32 chip, right? Pins 40 and 41 I think?

**Comment by mmakaay** [comment]
Sorry for the late response, I must have missed the notification in my mail.
In the below image, you can see the pins that provide RX/TX.
Those are indeed 40 and 41.

![afbeelding](https://user-images.githubusercontent.com/470371/159249632-a839b9e3-4364-4f08-9795-4d26d6a499fe.png)

**Comment by mmakaay** [comment]
Closing this issue, I presume the info is sufficient to get going?

**Comment by rufik** [comment]
Yes, sure, thanks a lot!
